### ISSUE TITLE
kvm_ivshmem/uio_ivshmem support

### ISSUE THREAD

**Issue by MoeMahhouk** [henning-schild-work/ivshmem-guest-code#9]
Hello,

I know it's been a while now but i am very interested in this work.
I have been searching for a way for a communication through shared memory between minimal VMs that only contain a preconfigured Linux and an agent with execution runtime.
Therefore, your work here sounded really related to my research and it would be great if you can help me answer some of my concernings:
1- is there an interface or a library to use your uio_ivshmem kernel module in VMs with preconfigured minimal Linux?
2- is it necessary for the extra doorbell server to enable multiple VMs to communicate through a specific shared memory?

Unfortunately, i couldn't find any support or usefull examples for the qemu ivshmem feature and it seems to be deprecated and/or not completely supported anymore. The DPDK remove the ivshmem library after DPDK version 16.04.

Thanks again and hope to hear from you soon :)
Best regards

**Comment by henning-schild** [comment]
The repository is not actively maintained, it just exists so hold the uio driver for jailhouse in a branch.

1. there is https://github.com/henning-schild-work/ivshmem-guest-code/tree/master/uio/tests/Interrupts/VM uio_read and uio_write

and in the jailhouse branch there is a python example
https://github.com/henning-schild-work/ivshmem-guest-code/blob/jailhouse/tests/shmem_test.py

2. i never worked with the doorbell server, only one-to-one and basically only on jailhouse

Using this is strongly discouraged. It is legacy and has severe limitations. You could google for ivsmem2 and see if you want to base your research on that. And if your use-case does not absolutely required shared memory, i would use "network" as basis for inter-VM-communication.

**Comment by MoeMahhouk** [comment]
Thanks for the fast response.
I will look into your references and recommendation :+1: 
We already have implemented an inter-VM-communication through VSock but in order to optimize the performance we thought of using shared memory to see if that would make a huge difference or not.
Thanks again for your Feedback.
